Update of configuration.md
LightTable/user-guide pull request #1
Opened 2017-05-05 15:36 UTC by MarcusE1W

updated link to codemirror and enhanced the description how to use themes

2017-05-16 18:38 UTC, MarcusE1W commented
This is a small test request. Let me know if the approach is ok.

2017-05-18 01:43 UTC, sbauer322 commented
I'll be able to check this out over the weekend, sorry for the delay on this and the other PRs you opened!

2017-05-22 03:54 UTC, sbauer322 requested changes
Just a few minor changes and this looks good to me! Thank you!

2017-05-22 03:54 UTC, sbauer322 commented on configuration.md
> +You have two options, many third party theme packages can be found in the plugin manager.
Could you clarify what the two options are? This line seems out of place.

2017-05-22 03:54 UTC, sbauer322 commented on configuration.md
> +2. check if the local LightTable user themes folder  .config/LightTable/User/core/css/themes/ already exists
Wrap .config/LightTable/User/core/css/themes/ with \`... so:

`.config/LightTable/User/core/css/themes/`

2017-05-22 03:54 UTC, sbauer322 commented on configuration.md
> +### Change settings (e.g., fonts, line numbers)?
The '?' can be removed from this heading and in all the other headings below.

2017-05-23 19:38 UTC, MarcusE1W commented on configuration.md
> +### Change settings (e.g., fonts, line numbers)?
done, all '?' removed

2017-05-23 19:40 UTC, MarcusE1W commented on configuration.md
> +You have two options, many third party theme packages can be found in the plugin manager.
I have changed the sentence a bit, without dwelling on the options...

2017-05-23 19:40 UTC, MarcusE1W commented on configuration.md
> +2. check if the local LightTable user themes folder  .config/LightTable/User/core/css/themes/ already exists
done

2017-05-23 19:57 UTC, MarcusE1W commented
So, the changes are done 

- [x] ? removed

- [x] Two options... sentence rephrased

- [x] .config/... marked as code

2017-05-23 19:58 UTC, MarcusE1W commented
ups, I closed the request accidentially for a moment. open again

2017-06-29 10:32 UTC, MarcusE1W commented
Do you think this could be reviewed again ?

2017-12-06 11:15 UTC, closed without merging

2017-12-06 11:16 UTC, MarcusE1W commented
Seems not to happen